### ISSUE TITLE
Cannot find JS plugin

### ISSUE THREAD

**Issue by peterjhart** [carsdotcom/gulp-sonar#14]
```
[09:20:18] ERROR: Error during Sonar runner execution

[09:20:18] org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)

[09:20:18] 	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
[09:20:18] 
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)

[09:20:18] 	at org.sonar.runner.Main.executeTask(Main.java:70)
[09:20:18] 
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
Caused by: You must install a plugin that supports the language 'js'
[09:20:18] 

[09:20:18] Return code: 1.

/Users/ … /node_modules/gulp-sonar/index.js:73
                        throw new PluginError('gulp-sonar', format('Return code: %d.', code));
                        ^
Error: Return code: 1.
```

Configuration from gulpfile:

```

			var options = {
				sonar: {
					host: {
						url: 'https://internal/sonar/'
					},
					/*
					jdbc: {
						url: 'jdbc:mysql://localhost:3306/sonar',
						username: 'sonar',
						password: 'sonar'
					},
					*/
					projectKey: 'com.stuff:2.0.0-rc1',
					projectName: 'Stuff 2.0',
					projectVersion: '2.0.0-rc1',
					// comma-delimited string of source directories
					sources: 'dist/js,test/',
					language: 'js',
					sourceEncoding: 'UTF-8',
					javascript: {
						lcov: {
							reportPath: 'reports/sonar/lcov/lcov.info'
						}
					},
					exec: {
						// All these properties will be send to the child_process.exec method (see: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback )
						// Increase the amount of data allowed on stdout or stderr (if this value is exceeded then the child process is killed, and the gulp-sonar will fail).
						maxBuffer: 1024 * 1024
					}
				}
			};
```

I tried setting language to 'javascript', but had the same problem. Setting it to 'java' successfully created a report and uploaded to our Sonar server, but of course everything was 0.

**Comment by peterjhart** [comment]
Oh! The javascript plugin needs to be installed on the _remote sonar server_, not locally. I didn't realize that the error happened after the sonar runner tried to upload a report.

Installing the javascript plugin on our sonar server fixed the problem.
