### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by fsmaia** [carsdotcom/gulp-sonar#24]
I'm getting this error:

>
java.lang.UnsupportedClassVersionError:
 org/sonarsource/scanner/cli/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.sonarsource.scanner.cli.Main. Program will exit.

Then I tried to logging the `SONAR_SCANNER_COMMAND` and running it manually and everything went fine.

**Comment by fsmaia** [comment]
Reading further I concluded that my `PATH` variable is being slightly modified when I run the command via NPM. Probably the `JAVA_HOME` variable is being changed to a older JDK version,
