### ISSUE TITLE
Return code 1 in gulp-sonar 3.0.0

### ISSUE THREAD

**Issue by joysarkarhub** [carsdotcom/gulp-sonar#25]
I have gulp-sonar 3.0.0 with Sonarqube 5.3 and JavaScript plugin version 2.10.we get the following error in our build scripts:

11:42:44] 11:42:44.510 ERROR: Error during SonarQube Scanner execution

[11:42:44] java.lang.IllegalStateException: Report processing is taking longer than the configured wait limit.
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:165)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:108)

[11:42:44] Return code: 1.

/development/workspace/<PROJECT_NAME>/node_modules/gulp-sonar/index.js:74
                        throw new PluginError('gulp-sonar', format('Return code: %d.', code));
                        ^
Error: Return code: 1.

**Comment by machellerogden** [comment]
Please try again with the latest version.
